framework for sibling call check and rpm / src tree specification
Signed-off-by: Ryan Sullivan <rysulliv@redhat.com>

diff --git a/kpatch-analyze/kpatch-analyze b/kpatch-analyze/kpatch-analyze
--- a/kpatch-analyze/kpatch-analyze
+++ b/kpatch-analyze/kpatch-analyze
@@ -43,7 +43,6 @@ CHANGEDFILES=
 PATCHFILE=
 TOOLSDIR=
 
-
 warn() {
 	echo "WARNING: $1" >&2
 }
@@ -90,6 +89,22 @@ find_dirs() {
 	else
 		return 1
 	fi
+}
+
+extract_rpm()
+{
+	local rpm_src
+	local kern_name
+	local linux_name
+	local arch
+
+	rpm_src="$1"
+	kern_name="${rpm_src%.src.rpm}"
+	linux_name="linux${kern_name#kernel}.$(uname -m)"
+
+	rpm -ivh "$rpm_src"
+	rpmbuild --nodeps -bp "$HOME/rpmbuild/SPECS/kernel.spec"
+	SRC="$HOME/rpmbuild/BUILD/$kern_name/$linux_name/"
 }
 
 git_init() {
@@ -155,10 +170,13 @@ usage() {
 	echo "		-d, --debug             Enable 'xtrace' and keep scratch files" >&2
 	echo "		                        in <CACHEDIR>/tmp" >&2
 	echo "		                        (can be specified multiple times)" >&2
+	echo "		-s, --src               Specify alternative kernel source tree" >&2
+	echo "		-r, --rpm               Specify rpm from which to extract" >&2
+	echo "		                        kernel source tree" >&2
 	echo "		--skip-cleanup          Skip post-analysis cleanup" >&2
 }
 
-options="$(getopt -o hd -l "help,debug,skip-cleanup" -- "$@")" || die "getopt failed"
+options="$(getopt -o hds:r: -l "help,debug,src,rpm,skip-cleanup" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -173,6 +191,14 @@ while [[ $# -gt 0 ]]; do
 	if [[ $DEBUG -eq 1 ]]; then
 		echo "DEBUG mode enabled"
 	fi
+	;;
+	-s|--src)
+	SRCDIR=$2
+	shift
+	;;
+	-r|--rpm)
+	extract_rpm $2
+	shift
 	;;
 	--skip-cleanup)
 		echo "Skipping cleanup"
@@ -207,7 +233,7 @@ echo "LOGGER started" | logger 1
 
 [[ "$SKIPCLEANUP" -eq 0 ]] && trap cleanup EXIT INT TERM HUP
 
-[[ -d "$SRCDIR" ]] || die "$SRCDIR doesn't exist, try running: 'kpatch-build --skip-build $PATCHFILE' first"
+[[ -d "$SRCDIR" ]] || die "$SRCDIR doesn't exist, try running: 'kpatch-build --skip-build $PATCHFILE' first or specify a different source tree with '-s,--src' or an rpm to extract with '-r,--rpm'"
 find_dirs || die "can't find location of required 'kpatch-sparse' tool"
 
 cd "$SRCDIR" || die
