sparse: first analyser framework base
Signed-off-by: Divya Cote <divya.cote@gmail.com>

diff --git a/kpatch-build/kpatch-build b/kpatch-build/kpatch-build
--- a/kpatch-build/kpatch-build
+++ b/kpatch-build/kpatch-build
@@ -703,6 +703,8 @@ usage() {
 	echo "		                        specify current version of module" >&2
 	echo "		--oot-module-src        Specify out-of-tree module source directory" >&2
 	echo "		-R, --non-replace       Disable replace patch (replace is on by default)" >&2
+	echo "		--skip-build            Skip actual build" >&2
+	echo "		                        (prepare and verify patches only)" >&2
 	echo "		--skip-cleanup          Skip post-build cleanup" >&2
 	echo "		--skip-compiler-check   Skip compiler version matching check" >&2
 	echo "		                        (not recommended)" >&2
@@ -712,7 +714,7 @@ if ! command -v gawk &> /dev/null; then
 	die "gawk not installed"
 fi
 
-options="$(getopt -o ha:r:s:c:v:j:t:n:o:dR -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,oot-module:,oot-module-src:,debug,skip-gcc-check,skip-compiler-check,skip-cleanup,non-replace" -- "$@")" || die "getopt failed"
+options="$(getopt -o ha:r:s:c:v:j:t:n:o:dR -l "help,archversion:,sourcerpm:,sourcedir:,config:,vmlinux:,jobs:,target:,name:,output:,oot-module:,oot-module-src:,debug,skip-build,skip-gcc-check,skip-compiler-check,skip-cleanup,non-replace" -- "$@")" || die "getopt failed"
 
 eval set -- "$options"
 
@@ -782,6 +784,10 @@ while [[ $# -gt 0 ]]; do
 		;;
 	-R|--non-replace)
 		KLP_REPLACE=0
+		;;
+	--skip-build)
+		echo "Skipping build"
+		SKIPBUILD=1
 		;;
 	--skip-cleanup)
 		echo "Skipping cleanup"
@@ -1191,6 +1197,8 @@ fi
 echo "Testing patch file(s)"
 cd "$BUILDDIR" || die
 verify_patch_files
+
+[[ "$SKIPBUILD" -eq 1 ]] && exit 0
 apply_patches
 remove_patches
 
