kpatch-test: ignore orphan section warning
Ignores the orphan section warning that fills log files during normal
builds to cut down on log sizes and increase readability

Signed-off-by: Ryan Sullivan <rysulliv@redhat.com>

diff --git a/test/integration/kpatch-test b/test/integration/kpatch-test
--- a/test/integration/kpatch-test
+++ b/test/integration/kpatch-test
@@ -120,8 +120,10 @@ else
 fi
 
 error() {
-	echo "ERROR: $*" |tee -a $LOG >&2
-	ERROR=$((ERROR + 1))
+	if [[ $(echo $LOG | grep -q "orphan section") == 1 ]]; then
+		echo "ERROR: $*" |tee -a $LOG >&2
+		ERROR=$((ERROR + 1))
+	fi
 }
 
 log() {
